CREATE TABLE [dbo].[Users]
(
	[Id] NVARCHAR(128)  NOT NULL PRIMARY KEY, 
    [FirstName] NVARCHAR(60) NOT NULL, 
    [LastName] NVARCHAR(60) NOT NULL,
	[Email] NVARCHAR(120) NOT NULL, 
    [UserName] NVARCHAR(120) NOT NULL, 
    [PasswordHash] NVARCHAR(MAX) NOT NULL,
)
